// generate-data.js
import fs from 'fs'

// --- 1. THE GPU DATABASE (100+ GPUs) ---
const gpus = [
  // NVIDIA RTX 40 Series
  { id: 'rtx-4090', name: 'NVIDIA GeForce RTX 4090', score: 100, vram: 24 },
  {
    id: 'rtx-4080-super',
    name: 'NVIDIA GeForce RTX 4080 Super',
    score: 88,
    vram: 16
  },
  { id: 'rtx-4080', name: 'NVIDIA GeForce RTX 4080', score: 85, vram: 16 },
  {
    id: 'rtx-4070-ti-super',
    name: 'NVIDIA GeForce RTX 4070 Ti Super',
    score: 78,
    vram: 16
  },
  {
    id: 'rtx-4070-ti',
    name: 'NVIDIA GeForce RTX 4070 Ti',
    score: 72,
    vram: 12
  },
  {
    id: 'rtx-4070-super',
    name: 'NVIDIA GeForce RTX 4070 Super',
    score: 68,
    vram: 12
  },
  { id: 'rtx-4070', name: 'NVIDIA GeForce RTX 4070', score: 65, vram: 12 },
  {
    id: 'rtx-4060-ti-16gb',
    name: 'NVIDIA GeForce RTX 4060 Ti (16GB)',
    score: 56,
    vram: 16
  },
  { id: 'rtx-4060-ti', name: 'NVIDIA GeForce RTX 4060 Ti', score: 55, vram: 8 },
  { id: 'rtx-4060', name: 'NVIDIA GeForce RTX 4060', score: 46, vram: 8 },

  // NVIDIA RTX 30 Series
  {
    id: 'rtx-3090-ti',
    name: 'NVIDIA GeForce RTX 3090 Ti',
    score: 76,
    vram: 24
  },
  { id: 'rtx-3090', name: 'NVIDIA GeForce RTX 3090', score: 74, vram: 24 },
  {
    id: 'rtx-3080-ti',
    name: 'NVIDIA GeForce RTX 3080 Ti',
    score: 70,
    vram: 12
  },
  {
    id: 'rtx-3080-12gb',
    name: 'NVIDIA GeForce RTX 3080 (12GB)',
    score: 68,
    vram: 12
  },
  { id: 'rtx-3080', name: 'NVIDIA GeForce RTX 3080', score: 65, vram: 10 },
  { id: 'rtx-3070-ti', name: 'NVIDIA GeForce RTX 3070 Ti', score: 58, vram: 8 },
  { id: 'rtx-3070', name: 'NVIDIA GeForce RTX 3070', score: 54, vram: 8 },
  { id: 'rtx-3060-ti', name: 'NVIDIA GeForce RTX 3060 Ti', score: 48, vram: 8 },
  { id: 'rtx-3060', name: 'NVIDIA GeForce RTX 3060', score: 42, vram: 12 },
  { id: 'rtx-3050', name: 'NVIDIA GeForce RTX 3050', score: 28, vram: 8 },

  // NVIDIA RTX 20 Series
  {
    id: 'rtx-2080-ti',
    name: 'NVIDIA GeForce RTX 2080 Ti',
    score: 58,
    vram: 11
  },
  {
    id: 'rtx-2080-super',
    name: 'NVIDIA GeForce RTX 2080 Super',
    score: 49,
    vram: 8
  },
  { id: 'rtx-2080', name: 'NVIDIA GeForce RTX 2080', score: 46, vram: 8 },
  {
    id: 'rtx-2070-super',
    name: 'NVIDIA GeForce RTX 2070 Super',
    score: 44,
    vram: 8
  },
  { id: 'rtx-2070', name: 'NVIDIA GeForce RTX 2070', score: 39, vram: 8 },
  {
    id: 'rtx-2060-super',
    name: 'NVIDIA GeForce RTX 2060 Super',
    score: 38,
    vram: 8
  },
  { id: 'rtx-2060', name: 'NVIDIA GeForce RTX 2060', score: 34, vram: 6 },

  // NVIDIA GTX 16/10 Series (Most Popular)
  { id: 'gtx-1660-ti', name: 'NVIDIA GeForce GTX 1660 Ti', score: 30, vram: 6 },
  {
    id: 'gtx-1660-super',
    name: 'NVIDIA GeForce GTX 1660 Super',
    score: 29,
    vram: 6
  },
  { id: 'gtx-1660', name: 'NVIDIA GeForce GTX 1660', score: 26, vram: 6 },
  {
    id: 'gtx-1650-super',
    name: 'NVIDIA GeForce GTX 1650 Super',
    score: 22,
    vram: 4
  },
  { id: 'gtx-1650', name: 'NVIDIA GeForce GTX 1650', score: 18, vram: 4 },
  {
    id: 'gtx-1080-ti',
    name: 'NVIDIA GeForce GTX 1080 Ti',
    score: 45,
    vram: 11
  },
  { id: 'gtx-1080', name: 'NVIDIA GeForce GTX 1080', score: 35, vram: 8 },
  { id: 'gtx-1070-ti', name: 'NVIDIA GeForce GTX 1070 Ti', score: 32, vram: 8 },
  { id: 'gtx-1070', name: 'NVIDIA GeForce GTX 1070', score: 28, vram: 8 },
  {
    id: 'gtx-1060-6gb',
    name: 'NVIDIA GeForce GTX 1060 (6GB)',
    score: 20,
    vram: 6
  },
  {
    id: 'gtx-1060-3gb',
    name: 'NVIDIA GeForce GTX 1060 (3GB)',
    score: 18,
    vram: 3
  },
  { id: 'gtx-1050-ti', name: 'NVIDIA GeForce GTX 1050 Ti', score: 14, vram: 4 },
  { id: 'gtx-1050', name: 'NVIDIA GeForce GTX 1050', score: 11, vram: 2 },
  { id: 'gt-1030', name: 'NVIDIA GeForce GT 1030', score: 5, vram: 2 },

  // AMD Radeon RX 7000/6000
  { id: 'rx-7900-xtx', name: 'AMD Radeon RX 7900 XTX', score: 92, vram: 24 },
  { id: 'rx-7900-xt', name: 'AMD Radeon RX 7900 XT', score: 80, vram: 20 },
  { id: 'rx-7800-xt', name: 'AMD Radeon RX 7800 XT', score: 62, vram: 16 },
  { id: 'rx-7700-xt', name: 'AMD Radeon RX 7700 XT', score: 54, vram: 12 },
  { id: 'rx-7600', name: 'AMD Radeon RX 7600', score: 40, vram: 8 },
  { id: 'rx-6950-xt', name: 'AMD Radeon RX 6950 XT', score: 73, vram: 16 },
  { id: 'rx-6800-xt', name: 'AMD Radeon RX 6800 XT', score: 64, vram: 16 },
  { id: 'rx-6700-xt', name: 'AMD Radeon RX 6700 XT', score: 48, vram: 12 },
  { id: 'rx-6600-xt', name: 'AMD Radeon RX 6600 XT', score: 38, vram: 8 },
  { id: 'rx-6600', name: 'AMD Radeon RX 6600', score: 34, vram: 8 },

  // AMD Older
  { id: 'rx-5700-xt', name: 'AMD Radeon RX 5700 XT', score: 42, vram: 8 },
  { id: 'rx-5600-xt', name: 'AMD Radeon RX 5600 XT', score: 35, vram: 6 },
  { id: 'rx-580', name: 'AMD Radeon RX 580', score: 19, vram: 8 },
  { id: 'rx-570', name: 'AMD Radeon RX 570', score: 17, vram: 4 },

  // Intel Arc
  { id: 'arc-a770', name: 'Intel Arc A770', score: 44, vram: 16 },
  { id: 'arc-a750', name: 'Intel Arc A750', score: 39, vram: 8 },
  { id: 'arc-a380', name: 'Intel Arc A380', score: 15, vram: 6 },

  // Integrated
  { id: 'intel-uhd-770', name: 'Intel UHD Graphics 770', score: 4, vram: 0 },
  {
    id: 'amd-radeon-780m',
    name: 'AMD Radeon 780M (Handhelds)',
    score: 18,
    vram: 4
  }
]

// Add slugs and affiliate links automatically
const processedGPUs = gpus.map(gpu => ({
  ...gpu,
  slug: gpu.id,
  affiliateLink: `https://amazon.com/s?k=${gpu.name.replace(/ /g, '+')}&tag=myfps-20`
}))

// --- 2. THE GAME DATABASE (TIER SYSTEM) ---

const tiers = {
  // TIER S: Path Tracing / Next Gen (Requires 40-series or high 30-series for Ultra)
  S: { low: 40, med: 60, high: 80, ultra: 95 },
  // TIER A: Heavy AAA (Unreal Engine 5, Open World)
  A: { low: 30, med: 45, high: 65, ultra: 85 },
  // TIER B: Standard AAA (Well optimized, recent)
  B: { low: 20, med: 35, high: 50, ultra: 70 },
  // TIER C: Older AAA / Competitive Shooters (1080p Standard)
  C: { low: 10, med: 20, high: 30, ultra: 45 },
  // TIER D: Light Esports / Indie 3D
  D: { low: 5, med: 10, high: 15, ultra: 25 },
  // TIER E: 2D / Potato PC Friendly
  E: { low: 1, med: 3, high: 5, ultra: 10 }
}

const gameList = [
  // --- TIER S (EXTREME) ---
  { name: 'Cyberpunk 2077 (2.0)', tier: 'S' },
  { name: 'Alan Wake 2', tier: 'S' },
  { name: 'Black Myth: Wukong', tier: 'S' },
  { name: "Senua's Saga: Hellblade II", tier: 'S' },
  { name: "Dragon's Dogma 2", tier: 'S' },
  { name: 'Ark: Survival Ascended', tier: 'S' },
  { name: 'Avatar: Frontiers of Pandora', tier: 'S' },
  { name: 'Cities: Skylines II', tier: 'S' },
  { name: 'Microsoft Flight Simulator 2024', tier: 'S' },
  { name: 'Star Wars Outlaws', tier: 'S' },
  { name: 'Immortals of Aveum', tier: 'S' },
  { name: 'Lords of the Fallen (2023)', tier: 'S' },
  { name: 'Metro Exodus Enhanced Edition', tier: 'S' },
  { name: 'Portal with RTX', tier: 'S' },
  { name: 'Minecraft (RTX On)', tier: 'S' },

  // --- TIER A (HEAVY AAA) ---
  { name: 'Starfield', tier: 'A' },
  { name: 'Hogwarts Legacy', tier: 'A' },
  { name: 'The Last of Us Part I', tier: 'A' },
  { name: 'Red Dead Redemption 2', tier: 'A' },
  { name: 'God of War Ragnarok', tier: 'A' },
  { name: 'Horizon Forbidden West', tier: 'A' },
  { name: 'Ghost of Tsushima', tier: 'A' },
  { name: 'Elden Ring', tier: 'A' },
  { name: "Baldur's Gate 3", tier: 'A' },
  { name: 'Helldivers 2', tier: 'A' },
  { name: 'Final Fantasy XVI', tier: 'A' },
  { name: 'Final Fantasy VII Rebirth', tier: 'A' },
  { name: 'Resident Evil 4 Remake', tier: 'A' },
  { name: 'Dead Space Remake', tier: 'A' },
  { name: 'Silent Hill 2 Remake', tier: 'A' },
  { name: 'Tekken 8', tier: 'A' },
  { name: 'Mortal Kombat 1', tier: 'A' },
  { name: 'Street Fighter 6', tier: 'A' },
  { name: 'Armored Core VI', tier: 'A' },
  { name: 'A Plague Tale: Requiem', tier: 'A' },
  { name: 'Control', tier: 'A' },
  { name: 'Returnal', tier: 'A' },
  { name: 'Warhammer 40k: Darktide', tier: 'A' },
  { name: 'Warhammer 40k: Space Marine 2', tier: 'A' },
  { name: 'S.T.A.L.K.E.R. 2', tier: 'A' },
  { name: 'Total War: Warhammer III', tier: 'A' },
  { name: 'Forza Motorsport (2023)', tier: 'A' },
  { name: "Assassin's Creed Mirage", tier: 'A' },
  { name: 'Skull and Bones', tier: 'A' },
  { name: 'Suicide Squad: Kill the Justice League', tier: 'A' },
  { name: 'Gotham Knights', tier: 'A' },
  { name: "Marvel's Spider-Man 2", tier: 'A' },
  { name: "Marvel's Spider-Man Remastered", tier: 'A' },
  { name: "Marvel's Miles Morales", tier: 'A' },
  { name: 'Uncharted: Legacy of Thieves', tier: 'A' },
  { name: 'Ratchet & Clank: Rift Apart', tier: 'A' },
  { name: 'Dying Light 2', tier: 'A' },
  { name: 'Far Cry 6', tier: 'A' },
  { name: 'Watch Dogs: Legion', tier: 'A' },
  { name: 'Just Cause 4', tier: 'A' },
  { name: 'The Witcher 3 (Next Gen)', tier: 'A' },
  { name: 'Kingdom Come: Deliverance', tier: 'A' },
  { name: 'Mount & Blade II: Bannerlord', tier: 'A' },
  { name: 'Rust', tier: 'A' },
  { name: 'DayZ', tier: 'A' },
  { name: 'Scum', tier: 'A' },
  { name: 'Escape from Tarkov', tier: 'A' },
  { name: 'Hunt: Showdown', tier: 'A' },
  { name: 'Squad', tier: 'A' },
  { name: 'Hell Let Loose', tier: 'A' },
  { name: 'Ready or Not', tier: 'A' },
  { name: 'Gray Zone Warfare', tier: 'A' },
  { name: 'Manor Lords', tier: 'A' },

  // --- TIER B (STANDARD AAA / POPULAR) ---
  { name: 'Grand Theft Auto V', tier: 'B' },
  { name: 'Call of Duty: Modern Warfare III', tier: 'B' },
  { name: 'Call of Duty: Warzone', tier: 'B' },
  { name: 'Apex Legends', tier: 'B' },
  { name: 'Overwatch 2', tier: 'B' },
  { name: 'Rainbow Six Siege', tier: 'B' },
  { name: 'Destiny 2', tier: 'B' },
  { name: 'Warframe', tier: 'B' },
  { name: 'The Finals', tier: 'B' },
  { name: 'XDefiant', tier: 'B' },
  { name: 'Battlefield 2042', tier: 'B' },
  { name: 'Battlefield V', tier: 'B' },
  { name: 'Battlefield 1', tier: 'B' },
  { name: 'Star Wars Jedi: Survivor', tier: 'B' },
  { name: 'Star Wars Jedi: Fallen Order', tier: 'B' },
  { name: 'Hitman 3', tier: 'B' },
  { name: 'Deathloop', tier: 'B' },
  { name: 'Prey', tier: 'B' },
  { name: 'Dishonored 2', tier: 'B' },
  { name: 'Doom Eternal', tier: 'B' },
  { name: 'Wolfenstein II: The New Colossus', tier: 'B' },
  { name: 'Monster Hunter: World', tier: 'B' },
  { name: 'Monster Hunter Rise', tier: 'B' },
  { name: 'Dark Souls III', tier: 'B' },
  { name: 'Sekiro: Shadows Die Twice', tier: 'B' },
  { name: 'Lies of P', tier: 'B' },
  { name: 'Nioh 2', tier: 'B' },
  { name: 'Wo Long: Fallen Dynasty', tier: 'B' },
  { name: 'Devil May Cry 5', tier: 'B' },
  { name: 'Resident Evil Village', tier: 'B' },
  { name: 'Resident Evil 7', tier: 'B' },
  { name: 'Resident Evil 2 Remake', tier: 'B' },
  { name: 'Resident Evil 3 Remake', tier: 'B' },
  { name: 'Dead Island 2', tier: 'B' },
  { name: 'Back 4 Blood', tier: 'B' },
  { name: 'World War Z', tier: 'B' },
  { name: 'Aliens: Fireteam Elite', tier: 'B' },
  { name: 'Remnant 2', tier: 'B' },
  { name: 'Remnant: From the Ashes', tier: 'B' },
  { name: 'Outriders', tier: 'B' },
  { name: 'Borderlands 3', tier: 'B' },
  { name: "Tiny Tina's Wonderlands", tier: 'B' },
  { name: 'Fallout 4', tier: 'B' },
  { name: 'Fallout 76', tier: 'B' },
  { name: 'The Outer Worlds', tier: 'B' },
  { name: 'Mass Effect Legendary Edition', tier: 'B' },
  { name: 'Dragon Age: Inquisition', tier: 'B' },
  { name: 'Skyrim Special Edition', tier: 'B' },
  { name: "No Man's Sky", tier: 'B' },
  { name: 'Sea of Thieves', tier: 'B' },
  { name: 'Grounded', tier: 'B' },
  { name: 'Subnautica: Below Zero', tier: 'B' },
  { name: 'Satisfactory', tier: 'B' },
  { name: 'Forza Horizon 5', tier: 'B' },
  { name: 'Forza Horizon 4', tier: 'B' },
  { name: 'F1 24', tier: 'B' },
  { name: 'Need for Speed Unbound', tier: 'B' },
  { name: 'Need for Speed Heat', tier: 'B' },
  { name: 'Dirt Rally 2.0', tier: 'B' },
  { name: 'Assetto Corsa Competizione', tier: 'B' },
  { name: 'BeamNG.drive', tier: 'B' },
  { name: 'SnowRunner', tier: 'B' },
  { name: 'Farming Simulator 22', tier: 'B' },
  { name: 'Euro Truck Simulator 2', tier: 'B' },
  { name: 'American Truck Simulator', tier: 'B' },
  { name: 'FIFA 23 / FC 24', tier: 'B' },
  { name: 'NBA 2K24', tier: 'B' },
  { name: 'Madden NFL 24', tier: 'B' },
  { name: 'PGA Tour 2K23', tier: 'B' },
  { name: 'WWE 2K24', tier: 'B' },
  { name: 'Civilization VI', tier: 'B' },
  { name: 'Age of Empires IV', tier: 'B' },
  { name: 'Company of Heroes 3', tier: 'B' },
  { name: 'Anno 1800', tier: 'B' },
  { name: 'Frostpunk 2', tier: 'B' },
  { name: 'Jurassic World Evolution 2', tier: 'B' },
  { name: 'Planet Zoo', tier: 'B' },
  { name: 'Planet Coaster', tier: 'B' },
  { name: 'Sims 4 (With DLCs)', tier: 'B' },
  { name: 'Genshin Impact', tier: 'B' },
  { name: 'Honkai: Star Rail', tier: 'B' },
  { name: 'Wuthering Waves', tier: 'B' },
  { name: 'Tower of Fantasy', tier: 'B' },
  { name: 'Zenless Zone Zero', tier: 'B' },
  { name: 'Persona 3 Reload', tier: 'B' },
  { name: 'Persona 5 Royal', tier: 'B' },
  { name: 'Yakuza: Like a Dragon', tier: 'B' },
  { name: 'Like a Dragon: Infinite Wealth', tier: 'B' },
  { name: 'Judgement', tier: 'B' },
  { name: 'Lost Judgment', tier: 'B' },
  { name: 'Tales of Arise', tier: 'B' },
  { name: 'Granblue Fantasy: Relink', tier: 'B' },
  { name: 'Blue Protocol', tier: 'B' },
  { name: 'Throne and Liberty', tier: 'B' },
  { name: 'Black Desert Online', tier: 'B' },
  { name: 'New World', tier: 'B' },
  { name: 'Lost Ark', tier: 'B' },
  { name: 'Path of Exile 2', tier: 'B' },
  { name: 'Diablo IV', tier: 'B' },
  { name: 'Last Epoch', tier: 'B' },
  { name: 'V Rising', tier: 'B' },
  { name: 'Enshrouded', tier: 'B' },
  { name: 'Palworld', tier: 'B' },
  { name: 'Valheim', tier: 'B' },
  { name: 'Sons of the Forest', tier: 'B' },
  { name: 'The Forest', tier: 'B' },
  { name: 'Green Hell', tier: 'B' },
  { name: 'Raft', tier: 'B' },
  { name: 'Smalland', tier: 'B' },
  { name: 'Abiotic Factor', tier: 'B' },
  { name: 'Nightingale', tier: 'B' },
  { name: 'Icarus', tier: 'B' },
  { name: 'Conan Exiles', tier: 'B' },
  { name: 'Ark: Survival Evolved', tier: 'B' },
  { name: '7 Days to Die', tier: 'B' },
  { name: 'Project Zomboid (Heavily Modded)', tier: 'B' },
  { name: 'Teardown', tier: 'B' },
  { name: 'Besiege', tier: 'B' },
  { name: 'Kerbal Space Program 2', tier: 'B' },
  { name: 'Space Engineers', tier: 'B' },
  { name: 'Stormworks', tier: 'B' },
  { name: 'From the Depths', tier: 'B' },

  // --- TIER C (COMPETITIVE / OPTIMIZED / OLDER AAA) ---
  { name: 'Counter-Strike 2', tier: 'C' },
  { name: 'Valorant', tier: 'C' },
  { name: 'League of Legends', tier: 'C' },
  { name: 'Dota 2', tier: 'C' },
  { name: 'Fortnite (Performance Mode)', tier: 'C' },
  { name: 'Rocket League', tier: 'C' },
  { name: 'Team Fortress 2', tier: 'C' },
  { name: 'Overwatch 2 (Low Settings)', tier: 'C' },
  { name: 'Paladins', tier: 'C' },
  { name: 'Smite', tier: 'C' },
  { name: 'Dead by Daylight', tier: 'C' },
  { name: 'Phasmophobia', tier: 'C' },
  { name: 'Lethal Company', tier: 'C' },
  { name: 'Content Warning', tier: 'C' },
  { name: 'Among Us', tier: 'C' },
  { name: 'Fall Guys', tier: 'C' },
  { name: 'Human Fall Flat', tier: 'C' },
  { name: 'Gang Beasts', tier: 'C' },
  { name: 'Party Animals', tier: 'C' },
  { name: 'Pummel Party', tier: 'C' },
  { name: 'Crab Game', tier: 'C' },
  { name: "Garry's Mod", tier: 'C' },
  { name: 'Left 4 Dead 2', tier: 'C' },
  { name: 'Portal 2', tier: 'C' },
  { name: 'Half-Life 2', tier: 'C' },
  { name: 'Black Mesa', tier: 'C' },
  { name: 'Deep Rock Galactic', tier: 'C' },
  { name: 'Risk of Rain 2', tier: 'C' },
  { name: 'Gunfire Reborn', tier: 'C' },
  { name: 'Roboquest', tier: 'C' },
  { name: 'Borderlands 2', tier: 'C' },
  { name: 'Payday 2', tier: 'C' },
  { name: 'Killing Floor 2', tier: 'C' },
  { name: 'Warhammer: Vermintide 2', tier: 'C' },
  { name: 'Insurgency: Sandstorm', tier: 'C' },
  { name: 'Rising Storm 2: Vietnam', tier: 'C' },
  { name: 'Chivalry 2', tier: 'C' },
  { name: 'Mordhau', tier: 'C' },
  { name: 'For Honor', tier: 'C' },
  { name: 'Sea of Thieves (Low)', tier: 'C' },
  { name: 'World of Tanks', tier: 'C' },
  { name: 'World of Warships', tier: 'C' },
  { name: 'War Thunder', tier: 'C' },
  { name: 'Enlisted', tier: 'C' },
  { name: 'Crossout', tier: 'C' },
  { name: 'Eve Online', tier: 'C' },
  { name: 'Albion Online', tier: 'C' },
  { name: 'Runescape (RS3)', tier: 'C' },
  { name: 'Old School Runescape (HD Plugin)', tier: 'C' },
  { name: 'Guild Wars 2', tier: 'C' },
  { name: 'World of Warcraft (Retail)', tier: 'C' },
  { name: 'World of Warcraft (Classic)', tier: 'C' },
  { name: 'Final Fantasy XIV', tier: 'C' },
  { name: 'Elder Scrolls Online', tier: 'C' },
  { name: 'Star Wars: The Old Republic', tier: 'C' },
  { name: 'Lord of the Rings Online', tier: 'C' },
  { name: 'MapleStory', tier: 'C' },
  { name: 'Path of Exile', tier: 'C' },
  { name: 'Torchlight II', tier: 'C' },
  { name: 'Grim Dawn', tier: 'C' },
  { name: 'Titan Quest', tier: 'C' },
  { name: 'Diablo III', tier: 'C' },
  { name: 'Diablo II: Resurrected', tier: 'C' },
  { name: 'Hades', tier: 'C' },
  { name: 'Hades II', tier: 'C' },
  { name: 'Dead Cells', tier: 'C' },
  { name: 'Hollow Knight', tier: 'C' },
  { name: 'Ori and the Will of the Wisps', tier: 'C' },
  { name: 'Ori and the Blind Forest', tier: 'C' },
  { name: 'Cuphead', tier: 'C' },
  { name: 'Celeste', tier: 'C' },
  { name: 'Super Meat Boy', tier: 'C' },
  { name: 'The Binding of Isaac: Repentance', tier: 'C' },
  { name: 'Enter the Gungeon', tier: 'C' },
  { name: 'Slay the Spire', tier: 'C' },
  { name: 'Monster Train', tier: 'C' },
  { name: 'Balatro', tier: 'C' },
  { name: 'Inscryption', tier: 'C' },
  { name: 'Darkest Dungeon', tier: 'C' },
  { name: 'Darkest Dungeon II', tier: 'C' },
  { name: 'Cult of the Lamb', tier: 'C' },
  { name: "Don't Starve Together", tier: 'C' },
  { name: 'Oxygen Not Included', tier: 'C' },
  { name: 'RimWorld', tier: 'C' },
  { name: 'Factorio', tier: 'C' },
  { name: 'Dwarf Fortress (Steam)', tier: 'C' },
  { name: 'Prison Architect', tier: 'C' },
  { name: 'Two Point Hospital', tier: 'C' },
  { name: 'Cities: Skylines (1)', tier: 'C' },
  { name: 'SimCity 4', tier: 'C' },
  { name: 'RollerCoaster Tycoon 3', tier: 'C' },
  { name: 'Planet Coaster (Low)', tier: 'C' },
  { name: 'Zoo Tycoon', tier: 'C' },
  { name: 'Spore', tier: 'C' },
  { name: 'The Sims 3', tier: 'C' },
  { name: 'Stardew Valley', tier: 'C' },
  { name: 'Terraria', tier: 'C' },
  { name: 'Minecraft (Java)', tier: 'C' },
  { name: 'Minecraft (Bedrock)', tier: 'C' },
  { name: 'Roblox', tier: 'C' },
  { name: 'Unturned', tier: 'C' },
  { name: 'Subnautica', tier: 'C' },
  { name: 'Raft (Low)', tier: 'C' },
  { name: 'Slime Rancher', tier: 'C' },
  { name: 'Slime Rancher 2', tier: 'C' },
  { name: 'House Flipper', tier: 'C' },
  { name: 'PowerWash Simulator', tier: 'C' },
  { name: 'PC Building Simulator', tier: 'C' },
  { name: 'Cooking Simulator', tier: 'C' },
  { name: 'Thief Simulator', tier: 'C' },
  { name: 'Car Mechanic Simulator', tier: 'C' },
  { name: 'Goat Simulator 3', tier: 'C' },
  { name: 'Untitled Goose Game', tier: 'C' },
  { name: 'Stray', tier: 'C' },
  { name: 'Kena: Bridge of Spirits', tier: 'C' },
  { name: 'Tunic', tier: 'C' },
  { name: 'Outer Wilds', tier: 'C' },
  { name: 'Firewatch', tier: 'C' },
  { name: 'What Remains of Edith Finch', tier: 'C' },
  { name: 'The Stanley Parable', tier: 'C' },
  { name: 'Superliminal', tier: 'C' },
  { name: 'Undertale', tier: 'C' },
  { name: 'Deltarune', tier: 'C' },
  { name: 'Omori', tier: 'C' },
  { name: 'Lisa: The Painful', tier: 'C' },
  { name: 'Yume Nikki', tier: 'C' },
  { name: 'Vampire Survivors', tier: 'C' },
  { name: 'Brotato', tier: 'C' },
  { name: 'Halls of Torment', tier: 'C' },
  { name: 'Loop Hero', tier: 'C' },
  { name: 'Dave the Diver', tier: 'C' },
  { name: 'Dredge', tier: 'C' },
  { name: 'Papers, Please', tier: 'C' },
  { name: 'Obra Dinn', tier: 'C' },
  { name: 'Disco Elysium', tier: 'C' },
  { name: 'Citizen Sleeper', tier: 'C' },
  { name: 'Pentiment', tier: 'C' },
  { name: 'Hi-Fi Rush', tier: 'C' },
  { name: 'Neon White', tier: 'C' },
  { name: 'Hotline Miami', tier: 'C' },
  { name: 'Hotline Miami 2', tier: 'C' },
  { name: 'Katana Zero', tier: 'C' },
  { name: 'Sanabi', tier: 'C' },
  { name: 'My Friend Pedro', tier: 'C' },
  { name: 'Superhot', tier: 'C' },
  { name: 'Ghostrunner', tier: 'C' },
  { name: "Mirror's Edge", tier: 'C' },
  { name: 'Dishonored', tier: 'C' },
  { name: 'Bioshock Remastered', tier: 'C' },
  { name: 'Bioshock Infinite', tier: 'C' },
  { name: 'Batman: Arkham Asylum', tier: 'C' },
  { name: 'Batman: Arkham City', tier: 'C' },
  { name: 'Batman: Arkham Knight', tier: 'C' },
  { name: 'Mad Max', tier: 'C' },
  { name: 'Shadow of Mordor', tier: 'C' },
  { name: 'Shadow of War', tier: 'C' },
  { name: 'Sleeping Dogs', tier: 'C' },
  { name: 'Yakuza 0', tier: 'C' },
  { name: 'Yakuza Kiwami', tier: 'C' },
  { name: 'Metal Gear Solid V', tier: 'C' },
  { name: 'Metal Gear Rising', tier: 'C' },
  { name: 'Nier: Automata', tier: 'C' },
  { name: 'Bayonetta', tier: 'C' },
  { name: 'Vanquish', tier: 'C' },
  { name: 'Spec Ops: The Line', tier: 'C' },
  { name: 'Max Payne 3', tier: 'C' },
  { name: 'LA Noire', tier: 'C' },
  { name: 'Bully', tier: 'C' },
  { name: 'Manhunt', tier: 'C' },
  { name: 'Grand Theft Auto IV', tier: 'C' },
  { name: 'Grand Theft Auto: San Andreas', tier: 'C' },
  { name: 'Saints Row: The Third', tier: 'C' },
  { name: 'Saints Row IV', tier: 'C' },
  { name: 'Just Cause 3', tier: 'C' },
  { name: 'Far Cry 3', tier: 'C' },
  { name: 'Far Cry 4', tier: 'C' },
  { name: 'Far Cry 5', tier: 'C' },
  { name: 'Far Cry Primal', tier: 'C' },
  { name: "Assassin's Creed IV: Black Flag", tier: 'C' },
  { name: "Assassin's Creed Unity", tier: 'C' },
  { name: "Assassin's Creed Syndicate", tier: 'C' },
  { name: "Assassin's Creed Origins", tier: 'C' },
  { name: "Assassin's Creed Odyssey", tier: 'C' },
  { name: "Assassin's Creed Valhalla", tier: 'C' },
  { name: 'Watch Dogs 2', tier: 'C' },
  { name: "Tom Clancy's The Division 2", tier: 'C' },
  { name: "Tom Clancy's Ghost Recon Wildlands", tier: 'C' },
  { name: "Tom Clancy's Ghost Recon Breakpoint", tier: 'C' },
  { name: 'Sniper Elite 4', tier: 'C' },
  { name: 'Sniper Elite 5', tier: 'C' },
  { name: 'Zombie Army 4', tier: 'C' },
  { name: 'Strange Brigade', tier: 'C' },
  { name: 'World War Z: Aftermath', tier: 'C' },
  { name: 'State of Decay 2', tier: 'C' },
  { name: 'Days Gone', tier: 'C' },
  { name: 'Mad Max', tier: 'C' },
  { name: 'Rage 2', tier: 'C' },
  { name: 'Generation Zero', tier: 'C' },
  { name: 'Terminator: Resistance', tier: 'C' },
  { name: 'RoboCop: Rogue City', tier: 'C' }
]

// --- 3. THE BUILDER LOGIC ---
const processedGames = gameList.map(game => ({
  id: game.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, ''),
  name: game.name,
  slug: game.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, ''),
  requirements: tiers[game.tier]
}))

// --- 4. OUTPUT TO FILES ---
fs.writeFileSync('data/gpus.json', JSON.stringify(processedGPUs, null, 2))
fs.writeFileSync('data/games.json', JSON.stringify(processedGames, null, 2))

console.log(`✅ Generated ${processedGPUs.length} GPUs`)
console.log(`✅ Generated ${processedGames.length} Games`)
